import type { GameMode } from "./types";
import {
  positionChannel,
  audioChannel,
  colorChannel,
  shapeChannel,
  numberChannel,
  wordChannel,
} from "./channels";

export const MODES: GameMode[] = [
  {
    id: "classic",
    name: "クラシック Dual N-Back",
    tagline: "位置と音、2つの刺激を同時に追う定番トレーニング",
    group: "基本",
    channels: [positionChannel, audioChannel],
    defaultN: 2,
    display: "grid",
    baseTrials: 20,
  },
  {
    id: "single-position",
    name: "シングル（位置）",
    tagline: "位置のみ。Dualが難しい場合の入門用",
    group: "基本",
    channels: [positionChannel],
    defaultN: 2,
    display: "grid",
    baseTrials: 20,
  },
  {
    id: "single-audio",
    name: "シングル（音）",
    tagline: "音のみ。目を閉じても遊べる聴覚トレーニング",
    group: "基本",
    channels: [audioChannel],
    defaultN: 2,
    display: "center",
    baseTrials: 20,
  },
  {
    id: "triple",
    name: "Triple N-Back",
    tagline: "位置・音・色の3刺激同時。上級者向け",
    group: "上級",
    channels: [positionChannel, audioChannel, colorChannel],
    defaultN: 2,
    display: "grid",
    baseTrials: 20,
  },
  {
    id: "variable",
    name: "Variable N-Back",
    tagline: "成績に応じてNが自動調整される適応モード",
    group: "上級",
    channels: [positionChannel, audioChannel],
    defaultN: 2,
    adaptive: true,
    display: "grid",
    baseTrials: 20,
  },
  {
    id: "arithmetic",
    name: "Arithmetic N-Back",
    tagline: "N回前の数字との合計が偶数か判断する計算モード",
    group: "バリエーション",
    channels: [numberChannel],
    defaultN: 1,
    display: "center",
    baseTrials: 20,
  },
  {
    id: "pattern",
    name: "Pattern N-Back",
    tagline: "図形のみの視覚モード。ミュート環境でも遊べる",
    group: "バリエーション",
    channels: [shapeChannel],
    defaultN: 2,
    display: "center",
    baseTrials: 20,
  },
  {
    id: "stroop",
    name: "Color-Word N-Back",
    tagline: "文字の意味と色がズレるストループ干渉つき変則モード",
    group: "バリエーション",
    channels: [wordChannel],
    defaultN: 2,
    display: "center",
    baseTrials: 20,
  },
];

export const findMode = (id: string): GameMode | undefined =>
  MODES.find((m) => m.id === id);
